/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentRouteImport } from './routes/agent'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as HomeRouteImport } from './routes/home'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as VaultRouteImport } from './routes/vault'
import { Route as ItemItemIdRouteImport } from './routes/item.$itemId'
import { Route as ReviewDocumentIdRouteImport } from './routes/review.$documentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRoute = AgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultRoute = VaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemItemIdRoute = ItemItemIdRouteImport.update({
  id: '/item/$itemId',
  path: '/item/$itemId',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewDocumentIdRoute = ReviewDocumentIdRouteImport.update({
  id: '/review/$documentId',
  path: '/review/$documentId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/auth': typeof AuthRoute
  '/home': typeof HomeRoute
  '/scan': typeof ScanRoute
  '/vault': typeof VaultRoute
  '/item/$itemId': typeof ItemItemIdRoute
  '/review/$documentId': typeof ReviewDocumentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/auth': typeof AuthRoute
  '/home': typeof HomeRoute
  '/scan': typeof ScanRoute
  '/vault': typeof VaultRoute
  '/item/$itemId': typeof ItemItemIdRoute
  '/review/$documentId': typeof ReviewDocumentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/auth': typeof AuthRoute
  '/home': typeof HomeRoute
  '/scan': typeof ScanRoute
  '/vault': typeof VaultRoute
  '/item/$itemId': typeof ItemItemIdRoute
  '/review/$documentId': typeof ReviewDocumentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agent'
    | '/auth'
    | '/home'
    | '/scan'
    | '/vault'
    | '/item/$itemId'
    | '/review/$documentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agent'
    | '/auth'
    | '/home'
    | '/scan'
    | '/vault'
    | '/item/$itemId'
    | '/review/$documentId'
  id:
    | '__root__'
    | '/'
    | '/agent'
    | '/auth'
    | '/home'
    | '/scan'
    | '/vault'
    | '/item/$itemId'
    | '/review/$documentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentRoute: typeof AgentRoute
  AuthRoute: typeof AuthRoute
  HomeRoute: typeof HomeRoute
  ScanRoute: typeof ScanRoute
  VaultRoute: typeof VaultRoute
  ItemItemIdRoute: typeof ItemItemIdRoute
  ReviewDocumentIdRoute: typeof ReviewDocumentIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent': {
      id: '/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault': {
      id: '/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof VaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/item/$itemId': {
      id: '/item/$itemId'
      path: '/item/$itemId'
      fullPath: '/item/$itemId'
      preLoaderRoute: typeof ItemItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review/$documentId': {
      id: '/review/$documentId'
      path: '/review/$documentId'
      fullPath: '/review/$documentId'
      preLoaderRoute: typeof ReviewDocumentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentRoute: AgentRoute,
  AuthRoute: AuthRoute,
  HomeRoute: HomeRoute,
  ScanRoute: ScanRoute,
  VaultRoute: VaultRoute,
  ItemItemIdRoute: ItemItemIdRoute,
  ReviewDocumentIdRoute: ReviewDocumentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
